# An√°lise de Dados com Pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

In [ ]:
df.head(10)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M
5,2025.0,EN,FT,Data Engineer,80000,USD,80000,US,0,US,M
6,2025.0,SE,FT,Data Scientist,185000,USD,185000,US,0,US,M
7,2025.0,SE,FT,Data Scientist,148000,USD,148000,US,0,US,M
8,2025.0,MI,FT,Data Scientist,135000,USD,135000,CA,0,CA,M
9,2025.0,MI,FT,Data Scientist,108000,USD,108000,CA,0,CA,M

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [ ]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [ ]:
df.shape

(133349, 11)

In [ ]:
linhas, colunas = df.shape[0], df.shape[1]
print("Linhas:", linhas)
print("Colunas:", colunas)

Linhas: 133349
Colunas: 11

In [ ]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

Index(['ano', 'nivel_experiencia', 'tipo_emprego', 'titulo_cargo', 'salario',
       'moeda_salario', 'salario_em_usd', 'residencia_empregado',
       'taxa_remoto', 'localizacao_empresa', 'tamanho_empresa'],
      dtype='object')

In [ ]:
df["nivel_experiencia"].value_counts()

nivel_experiencia
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [ ]:
df["tipo_emprego"].value_counts()

tipo_emprego
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [ ]:
df["taxa_remoto"].value_counts()

taxa_remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [ ]:
df["tamanho_empresa"].value_counts()

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

nivel_experiencia
Senior       77241
Pleno        40465
Junior       12443
Executivo     3200
Name: count, dtype: int64

tipo_emprego
Tempo Integral    132563
Contrato             394
Meio Per√≠odo         376
Freelancer            16
Name: count, dtype: int64

taxa_remoto
Presencial    105312
Remoto         27718
H√≠brido          319
Name: count, dtype: int64

In [ ]:
df['tamanho_empresa'] = df['tamanho_empresa'].replace({
    'M': 'M√©dio',
    'L': 'Grande',
    'S': 'Pequeno'
})
display(df['tamanho_empresa'].value_counts())

tamanho_empresa
M√©dio      129561
Grande       3574
Pequeno       214
Name: count, dtype: int64

In [ ]:
df.head()

,ano,nivel_experiencia,tipo_emprego,titulo_cargo,salario,moeda_salario,salario_em_usd,residencia_empregado,taxa_remoto,localizacao_empresa,tamanho_empresa
0,2025.0,Senior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M√©dio
1,2025.0,Senior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M√©dio
2,2025.0,Pleno,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M√©dio
3,2025.0,Pleno,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M√©dio
4,2025.0,Junior,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M√©dio

In [ ]:
df.describe(include="object")

,nivel_experiencia,tipo_emprego,titulo_cargo,moeda_salario,residencia_empregado,taxa_remoto,localizacao_empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,Senior,Tempo Integral,Data Scientist,USD,US,Presencial,US,M√©dio
freq,77241,132563,17314,126140,119579,105312,119641,129561

In [ ]:
df.descrive()

AttributeError: 'DataFrame' object has no attribute 'descrive'

In [ ]:
df.describe()

                 ano       salario  salario_em_usd
count  133339.000000  1.333490e+05   133349.000000
mean     2024.358770  1.632833e+05   157617.272098
std         0.680627  2.173860e+05    74288.363097
min      2020.000000  1.400000e+04    15000.000000
25%      2024.000000  1.060200e+05   106000.000000
50%      2024.000000  1.470000e+05   146206.000000
75%      2025.000000  1.990000e+05   198000.000000
max      2025.000000  3.040000e+07   800000.000000